### ISSUE TITLE
Cannot Get Variable Type from PHPDoc Comment

### ISSUE THREAD

**Issue by mtangoo** [robertop/pelet#11]
I'm catching Variable found with code below. Everytime PHPDoc type (p1 and p2)  is empty wile I can happily see p3 comment just fine. I tried to trace myself but I get no where as I'm still learning how the library does things.
The code I use is this:
```php
<?php

namespace app\controllers;

use yii\web\Controller; 
/**@var $this yii\db\ActiveQuery */ 
 
class MeController extends Controller
{ 
    /**
     * @link http://www.yiiframework.com/
     * @copyright Copyright (c) 2008 Yii Software LLC
     * @license http://www.yiiframework.com/license/
     */
     private static $itsme = "My Full Name";
     
     public function test1()
     { 
         $me = $db->getQuery();
         $me-> //WANT TO GET $me as type of yii\db\ActiveQuery
         
     }
     
     public function test2()
     {
           
     }
}
```
I have tried to move PHPDoc to variable like
```php
/**@var $me yii\db\ActiveQuery */ 
         $me = $db->getQuery();
         $me->
```
it does not work. I have tried variances like `/*@var $me yii\db\ActiveQuery */ ` and every combination I can think of but with no avail. Comments on the method on sources says:
>The name of the "type" of this variable that was parsed out of the PHPDoc. For example  when a variable is decorated with " \@var $var TypeClass" comments

But that format ie : 

```php 
/**\@var $this yii\db\ActiveQuery */ 
         $me = $db->getQuery();
         $me->
```
does not work also!

Am I missing something? Also is it possible to add method that will receive only PHPDoc comments just like we do with variables? and then it will be easier to deal with them.
Thanks for great library.

```cpp
VariableFound(const UnicodeString& namespaceName,
              const UnicodeString& className,
              const UnicodeString& methodName,
              const pelet::VariableClass& variable,
              pelet::ExpressionClass* expression,
              const UnicodeString& comment)
{
    wxString name = ConvertTowx(variable.ChainList[0].Name);

    if(name!=m_variable)
        return;

    if(pelet::ExpressionClass::NEW_CALL == expression->ExpressionType)
    {
        pelet::NewInstanceExpressionClass* srcVariable = (pelet::NewInstanceExpressionClass*)expression;
        m_expressions.Add(ConvertTowx(srcVariable->ClassName));
    }
    else if(pelet::ExpressionClass::ARRAY == expression->ExpressionType)
    {

    }
    else if(pelet::ExpressionClass::SCALAR == expression->ExpressionType)
    {

    }
    else if(pelet::ExpressionClass::VARIABLE == expression->ExpressionType)
    {
        pelet::VariableClass* srcVariable = (pelet::VariableClass*)expression;

        wxString p1 = ConvertTowx(srcVariable->PhpDocType);
        wxString p2 = ConvertTowx(variable.PhpDocType);
        wxString p3 = ConvertTowx(comment);
    }
}
```

**Comment by robertop** [comment]
when pelet sees code like this:

```php
    /* @var $me yii\db\ActiveQuery */ 
    $me = $db->getQuery();
```

There will be 2 calls to the `VariableFound` callback; once for the doc comment and once for the assignment. I see that the variable it is being reported as a scalar (since there is no assignment). But looking at it now, this behavior is probably wrong.

I also see another error, PHP doc comments in the form `/**  */` are not being parsed for vars.

I'll try to fix in a bit.

**Comment by robertop** [comment]
Type hints are now being parsed out of both PHP doc comments and regular comments. Either of these should work:

```
    /* @var $me yii\db\ActiveQuery */ 
    /** @var $me yii\db\ActiveQuery */ 
```
In the `VariableFound` callback, a variable typehint can be detected if the `variable.IsPhpDocVariable` is set to true.
 
```
VariableFound(const UnicodeString& namespaceName,
              const UnicodeString& className,
              const UnicodeString& methodName,
              const pelet::VariableClass& variable,
              pelet::ExpressionClass* expression,
              const UnicodeString& comment)
{
    UnicodeString type;
    if (variable.IsPhpDocVariable && !variable.PhpDocType.isEmpty()) {
        type += UNICODE_STRING_SIMPLE("Variable is decorated with a PHPDoc comment: ");
        type += variable.PhpDocType;
    }
}
```

**Comment by mtangoo** [comment]
Thanks so much. I really appreciate. If you can write a summary of how things work with this library including pictorial interactive diagram it'll be great. I want to know it and help but I don't know it. 
Thanks again

**Comment by mtangoo** [comment]
I can confirm all is well right now.
Thanks!

**Comment by mtangoo** [comment]
Hi @robertop ,
I found this bug. When you have PHPDocs that follow each other line by line it picks only the last one. Here it will pick only $exception leaving the rest.
```php

/* @var $this \yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */
```

the Whole file is
```php
<?php

/* @var $this \yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

```

**Comment by mtangoo** [comment]
Bump :+1:  @robertop

**Comment by robertop** [comment]
I made an update to support multiple consecutive comments. This should be fixed now.

**Comment by mtangoo** [comment]
Thank you so much!
