### ISSUE TITLE
Which libraries for ICU are necessary?

### ISSUE THREAD

**Issue by mtangoo** [robertop/pelet#12]
When I compile Pelet I compile ICU also. The problem is ICU have many (and some are big) libraries. Currently am linking almost all of them. I wanted to know which of the library are essential to Pelet so that I include only those.

Thanks!

**Comment by robertop** [comment]
I build pelet with the help of the `icu-config` binary, that binary can be used to lists the linked libraries. 

    icu-config  --ldflags --ldflags-icuio

I believe the answer to your question is:

icui18n
icuuc
icudata
icuio

These are for ICU version 54.1.

**Comment by mtangoo** [comment]
Thank you again!
