### ISSUE TITLE
Option to disable test and sample

### ISSUE THREAD

**Issue by mtangoo** [robertop/pelet#14]
When I compile Pelet according to instruction it automatically compiles test and runs them.
Please if you find time, add the option to turn off. I tried but due to my zero knowledge in Lua, I failed miserably!

**Comment by robertop** [comment]
You should be able to build just the library (without the sample or tests) in this way

```
    make config=Release pelet
```

Let me know if this does not work for you.

**Comment by mtangoo** [comment]
Ok let me test

**Comment by mtangoo** [comment]
this does not work. Here is the full command
` premake4 --icu-config=`readlink -f ../libicu/bin/icu-config` gmake && cd build/gmake && make config=release pelet`

**Comment by mtangoo** [comment]
this one works

premake4 --icu-config=`readlink -f ../libicu/bin/icu-config` gmake && cd build/gmake && make  pelet
